<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="bonree-PC" name="registerTest" tests="5" failures="1" timestamp="19 Mar 2018 07:40:21 GMT" time="98.399" errors="0">
  <testcase name="test" time="28.2" classname="com.lemon.app.WechatLoginCase">
    <failure type="java.lang.AssertionError" message="expected [手机号码错误] but found [注册失败]">
      <![CDATA[java.lang.AssertionError: expected [手机号码错误] but found [注册失败]
	at com.lemon.app.WechatLoginCase.test(WechatLoginCase.java:25)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="31.583" classname="com.lemon.app.WechatLoginCase"/>
  <testcase name="test2" time="7.214" classname="com.lemon.app.WechatLoginCase"/>
  <testcase name="test2" time="12.532" classname="com.lemon.app.WechatLoginCase"/>
  <testcase name="test2" time="18.209" classname="com.lemon.app.WechatLoginCase"/>
</testsuite> <!-- registerTest -->
