<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="bonree-PC" name="registerTest" tests="5" failures="1" timestamp="20 Mar 2018 01:29:30 GMT" time="90.788" errors="0">
  <testcase name="test" time="25.773" classname="com.lemon.app.WechatLoginCase">
    <failure type="java.lang.AssertionError" message="expected [手机号码错误] but found [注册失败]">
      <![CDATA[java.lang.AssertionError: expected [手机号码错误] but found [注册失败]
	at com.lemon.app.util.Assertion.assertEquals(Assertion.java:11)
	at com.lemon.app.WechatLoginCase.test(WechatLoginCase.java:29)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="test" time="29.897" classname="com.lemon.app.WechatLoginCase"/>
  <testcase name="test2" time="6.6" classname="com.lemon.app.WechatLoginCase"/>
  <testcase name="test2" time="11.139" classname="com.lemon.app.WechatLoginCase"/>
  <testcase name="test2" time="16.678" classname="com.lemon.app.WechatLoginCase"/>
</testsuite> <!-- registerTest -->
